### ISSUE TITLE
Add instructions on how to retrieve API key

### ISSUE THREAD

**Issue by mylesagray** [mylesgray/homebridge-blueair#10]
API key was originally found using Charles proxy, unsure if this is global or is actually unique.

**Comment by krmkrx** [comment]
Hello there. Can you elaborate on how to find the API key using Charles Proxy? I am getting my Blueair soon and want to use your plugin. Thank you.

**Comment by mylesagray** [comment]
@krmkrx done: https://github.com/mylesgray/homebridge-blueair/wiki/API_Key

Closes #10

**Comment by krmkrx** [comment]
Hi there. I retrieved my API key. If I can direct message you somehow, we could check if the API key is global.

**Comment by mylesagray** [comment]
@krmkrx are you on the Homebridge Slack? Get me on there :)

**Comment by krmkrx** [comment]
Done!
