### ISSUE TITLE
Possible bug when changing fan speed 

### ISSUE THREAD

**Issue by ndlaham** [mylesgray/homebridge-blueair#16]
mylesgray, I wanted to start a new topic for this so we can keep the last thread we were discussing it on closed.

I was trying to reproduce this issue tonight and realized it might have to do with situations where I change the fan speed on the Blueair unit itself, and the Home app hasn’t updated/synced to the new state. I think when I do this, and then I go change the speed in HomeKit, things get squirrelly. 

I usually get unexpected results going from the highest speed 3, to around 30-35% on the slider. The fan will sometimes physically switch to speed 1, and then jump back to 2 right away. It’s hard to say exactly what percent the slider is on but it’s close to 1/3, and that’s when I see this glitch.

As I was testing, if I have the Home app’s fan speed selection on the screen, (let’s say on low), then I change the speed to High by pressing the physical button on the Blueair unit twice, the Honekit GUI won’t update to reflect the new state. It seems the Home app only updates the status if I kill the entire app and reopen it. 

I’m not 100% sure yet if the bug I’m experiencing is related to that or not, but I will play around with it more and see if I can reliable reproduce the issue every time. If I can, I’ll post my steps and take a video.

Otherwise it’s really not a big deal as I have to screw around with it outside of a normal way of using it to get it to happen. I think in normal, everyday use, this fan speed jump I am seeing is unlikely to happen.

In any case, I think the issue could stem from the mystery state of the slider switch on the Home app. Because it’s a variable switch and you cannot see a percentage and sort of have to guess, I just can’t tell if I’m misinterpreting something, or if the logic is getting confused.

It would actually be really nice from a user interface perspective if there was a UI switch for a 3 speed selector, instead of a 0-100% sliding switch (intended for a dimmer switch). If there was something like this with 4 hard states (Off, 1, 2 and 3), I think this could solve my issue and possibly simplify the programming logic. Does HomeKit have any configuration settings for this sort of switch with multiple hard states? 

I wonder what the HomeKit-enabled Hunter ceiling fans do, since most fans have low, medium, high and off?

Food for thought.

**Comment by mylesagray** [comment]
I have seen this behaviour myself actually now you have described it - this is related to #3 - currently the plugin will only poll the device for changed values on the hardware when the app is closed and opened - there is no "push" mechanism available from BlueAir's API that would allow me to automatically change values in the app based on your inputs to the physical device.

As such it will need to be a polling "pull" type method where I will poll the BlueAir API for changes every `n` seconds or such - however, I don't want to spam the API needlessly.

In addition, some investigation needs to be done about the different methods Homebridge can use to set values of characteristics as in the above issue.

On your question of the 0-100% vs 0, 1, 2 and 3 settings - I agree and that is what I originally wanted to do, however the HomeKit spec doesn't allow for those arbitrary levels and instead only allows me to specify a percentage - as such I had to write some logic to convert the percentage into the 0, 1, 2 and 3 levels the devices supports. See here:

https://github.com/mylesgray/homebridge-blueair/blob/791504d8c21345d037b68ec0c2deeb918c3803df/index.js#L916-L940

So if you want level 1 - anywhere between 1-33%, level 2 is between 34-66% and level 3 is 67-100%.

Happy to be told if there is another way to achieve this - looking at the `Fan` and `Fan v2` services they still use `Characteristic.RotationSpeed` which is a percentage slider: 

https://github.com/KhaosT/HAP-NodeJS/blob/9eaea6df40811ccc71664a1ab0c13736e759dac7/lib/gen/HomeKitTypes.js#L2881-L2919

**Comment by ndlaham** [comment]
I did a little looking and confirmed what you are seeing too by looking at Hunter’s fans. I found that officially supported HomeKit ceiling fans also use the 0-100% sliding switch, so that answers that unfortunately.
https://www.google.com/amp/s/9to5mac.com/2017/11/20/review-hunter-simpleconnect-ceiling-fan-homekit/amp/

Just floating another idea - It might not make sense, but what about using thermostat “Mode” state buttons like the Homebridge-Nest plugin uses (Off, Heat, Cool, Auto)? There are 4 buttons, and assuming they can be renamed, could you assign each button to one of the Blueair fan levels?

**Comment by mylesagray** [comment]
Good idea, but the `mode` state like you get on the heater accessory types aren't supported on the air purifier type we are using - you are also not able to change the labels on them I'm afraid.

The only characteristics I can attach to the air purifier type are here, and as far as I can see - none really make that easier:

https://github.com/KhaosT/HAP-NodeJS/blob/9eaea6df40811ccc71664a1ab0c13736e759dac7/lib/gen/HomeKitTypes.js#L2673-L2692

I myself have just adjusted to setting the fan to 25%-ish if I want level 1, 50%-ish if I want level 2 and 100% if I want level 3.

**Comment by ndlaham** [comment]
Got it. Yeah I’m starting to realize that and have also been trying to adjust the slider to somewhere that is visually clear you are in the correct range.

It would be nice if Apple’s UI would just tell you the percentage of wherever the slider lands. I’m sure they will make improvements over time though and offer some better options as new Homekit devices come out.

**Comment by mylesagray** [comment]
I think it actually does that on the Mojave version of the Home app, maybe
on iPad too?

Still, I think we are doing pretty alright with how it is working at the
moment :)

**Comment by ndlaham** [comment]
No doubt, I’m very happy with it. Thanks for all the hard work you have done and the ongoing improvements!
