### ISSUE TITLE
[FYI] I've forked your code over here for OpenHAB

### ISSUE THREAD

**Issue by alackmann** [mylesgray/homebridge-blueair#21]
Hi Myles - just an FYI that I've created a bunch of scripts and config to control the BlueAir 205 I have from the OpenHAB home automation server. It's here - https://bitbucket.org/alackmann/openhab-blueair/

Thanks for the work you've put in here. Couldn't have done mine without it.

**Comment by mylesagray** [comment]
Thanks for the note Andre! Much appreciated, glad the work I did is helping other communities out :)

I plan to longer-term extract the API calls into an importable library to make it a little more generic and abstract so there would be less boilerplate code in other implementations.

Any ideas you have around that would be more than welcome!
