### ISSUE TITLE
iOS 13 optimazation

### ISSUE THREAD

**Issue by motaker** [mylesgray/homebridge-blueair#24]
Hi, 
After iOS 13 update, I cannot access to fan speed auto mode, only fan speed sliders now.
Would you please optimize this plugin into iOS 13 ?

Thank you.

**Comment by mylesagray** [comment]
I noticed these too, it seems those attributes were removed from the iOS 13 home app, I will see if there are alternatives.

**Comment by mylesagray** [comment]
It appears this has just been removed from iOS 13's Home app screens - the characteristics and tagging have not changed, this is simply no-longer exposed in the UI.
