### ISSUE TITLE
HAP Warning

### ISSUE THREAD

**Issue by dsully** [mylesgray/homebridge-blueair#33]
Seeing this warning from the HAP library with Homebridge 1.1.2

> [8/27/2020, 6:58:26 PM] [BlueAir 280i] Initializing BlueAir accessory...
> HAP Warning: Characteristic 00000093-0000-1000-8000-0026BB765291 not in required or optional characteristics for  service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
> HAP Warning: Characteristic 00000065-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.
> HAP Warning: Characteristic undefined not in required or optional characteristics for service 0000008D-0000-1000-8000-0026BB765291. Adding anyway.

Looks like the "Carbon Dioxide Level" and others are not part of the "Air Quality Sensor" anymore?

**Comment by mylesagray** [comment]
Huh, interesting - it looks like AirQualSensor now supports "Density", not "Level":

https://developers.homebridge.io/#/service/AirQualitySensor

As for Carbon Dioxide, it looks like we may need to create a new sensor type:

https://developers.homebridge.io/#/service/CarbonDioxideSensor

Open to PRs :)

**Comment by dsully** [comment]
There is already a CarbonDioxideSensor created and in use. So just need to remove the bits from AirQualitySensor.

**Comment by dsully** [comment]
Ping

**Comment by dsully** [comment]
This fixes the issue as there is no longer `CarbonDioxideLevel` or `AirParticulateSize` characteristics as part of the AirQualitySensor service. You already have them separately as `PM2_5Density` and as part of the `CarbonDioxideSensor` service.

I also removed the white space changes (which should be fixed separately).

Thanks

**Comment by mylesagray** [comment]
Merged, thanks for the work!
