### ISSUE TITLE
Updated to Homebridge platform 

### ISSUE THREAD

**Issue by fjs21** [mylesgray/homebridge-blueair#47]
Hi @mylesagray,

As I was getting numerous warnings from Homebridge, I took a look at the blueair plugin to see if I could fix but then got a bit carried away.

I started working on a fork of your awesome plugin and recoded it using typescript as a dynamic platform type plugin. This way when you login, the BlueAir devices are detected and added as accessories automatically.

I also enabled configuration using the Homebridge UI so folks do not have to work with the json config directly. I also added some experimental code to allow people to hide devices that they do not want to wish to appear in Homebridge. This could also be extended to turn on/off support for features as you do.

https://github.com/fjs21/homebridge-blueair

**Comment by mylesagray** [comment]
Amazing work!

If you like, I can pull the changes into this repo and add you as a maintainer - rather than it living in a fork?

**Comment by fjs21** [comment]
I'm not very experienced with this but I'm not sure that a pull is the best option as it will break a lot of people's setups. Mine was working basically fine up as long as it ran in a bridge.

If you don't mind I could respond to the issues of others to direct them to my fork as an alternative? Quick change of the readme file may also work to direct people to the platform fork?

**Comment by mylesagray** [comment]
Sure that works too, if you want to open a PR for a readme update, I’ll merge it.

**Comment by fjs21** [comment]
I couldn't work out how to do the PR for just a single file and not blow up the entire repository. 

You could either use my readme.md file or just put a link to my repo in your readme. Sorry for the extra hassle.

**Comment by mylesagray** [comment]
Added a redirection to your plugin Fraser, i'm considering archiving this repo if you are done addressing the issues from users and redirecting them to your plugin?

**Comment by fjs21** [comment]
I’ll post a few more replies to the issues in your repo this am and you can go ahead at that point. This evening?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mylesagray** [comment]
Sounds good to me!
